export interface BMW {
  slug: string;
  naam: string;
  serie: string;
  pk: string;
  koppel: string;
  prijs: string;
  type: string;
  emoji: string;
  kleur: string;
  nieuw: boolean;
  motor: string;
  cilinderinhoud: string;
  nulHonderd: string;
  topsnelheid: string;
  verbruik: string;
  gewicht: string;
  aangedreven: string;
  introTekst: string;
  highlights: string[];
  doelgroep: string;
  gerelateerdeArtikelSlug?: string;
}

export const modellen: BMW[] = [
  {
    slug: "bmw-m3-competition",
    naam: "BMW M3 Competition",
    serie: "M Serie",
    pk: "510 pk",
    koppel: "650 Nm",
    prijs: "€105.000",
    type: "Sedan",
    emoji: "🏎️",
    kleur: "#1c69d4",
    nieuw: false,
    motor: "S58 3.0L Twin-Turbo zes-in-lijn",
    cilinderinhoud: "2.993 cc",
    nulHonderd: "3,9 sec (xDrive: 3,5 sec)",
    topsnelheid: "290 km/h (begrensd)",
    verbruik: "10,1 l/100 km",
    gewicht: "1.730 kg",
    aangedreven: "Achter (of xDrive vierwiel)",
    introTekst: "De BMW M3 Competition is het summum van praktisch rijgenot. Vier deuren, 510 pk en dagelijks bruikbaar — dit is waarom M GmbH bestaat. De S58-motor is technisch een van de beste zescilinders die ooit in een productieauto is gezet.",
    highlights: [
      "S58 twin-turbo motor — zelfde blok als de M4",
      "Optioneel xDrive vierwielaandrijving",
      "Carbon dakbekleding (Competition M xDrive)",
      "M Servotronic stuurbekrachtiging",
      "Adaptieve M onderstelling standaard",
    ],
    doelgroep: "Ideaal voor rijders die dagelijks comfortabel willen rijden én af en toe op het circuit willen staan. Vier deuren maken het ook geschikt als gezinsauto.",
    gerelateerdeArtikelSlug: "bmw-m3-vs-m4-welke-kiezen",
  },
  {
    slug: "bmw-m4-competition",
    naam: "BMW M4 Competition",
    serie: "M Serie",
    pk: "510 pk",
    koppel: "650 Nm",
    prijs: "€110.000",
    type: "Coupé",
    emoji: "🔥",
    kleur: "#e67e22",
    nieuw: false,
    motor: "S58 3.0L Twin-Turbo zes-in-lijn",
    cilinderinhoud: "2.993 cc",
    nulHonderd: "3,9 sec (xDrive: 3,5 sec)",
    topsnelheid: "290 km/h (begrensd)",
    verbruik: "10,4 l/100 km",
    gewicht: "1.725 kg",
    aangedreven: "Achter (of xDrive vierwiel)",
    introTekst: "De BMW M4 Competition is de emotionelere broer van de M3. Twee deuren, agressiever design en dezelfde S58-motor. Wat je verliest aan praktische deuren, win je terug in rijbeleving en uitstraling.",
    highlights: [
      "Iconisch coupé-silhouet met M-specifieke karosserieonderdelen",
      "Carbon keramische remmen als optie (M Carbon Keramik)",
      "Beschikbaar als Cabrio (M4 Competition Cabrio)",
      "M Compound remmen standaard — uitstekende remprestaties",
      "20/21 inch M smeedijzeren velgen",
    ],
    doelgroep: "Voor rijders die rijplezier boven praktische overwegingen stellen. Het design is uitgesproken en de coupé-beleving maakt elke rit bijzonder.",
    gerelateerdeArtikelSlug: "bmw-m3-vs-m4-welke-kiezen",
  },
  {
    slug: "bmw-m5-xdrive",
    naam: "BMW M5 xDrive",
    serie: "M Serie",
    pk: "727 pk",
    koppel: "1.000 Nm",
    prijs: "€165.000",
    type: "Sedan",
    emoji: "⚡",
    kleur: "#e74c3c",
    nieuw: true,
    motor: "S68 4.4L Twin-Turbo V8 + elektromotor (PHEV)",
    cilinderinhoud: "4.395 cc",
    nulHonderd: "3,5 sec",
    topsnelheid: "305 km/h (M Driver's Package)",
    verbruik: "4,8 l/100 km (WLTP gecombineerd)",
    gewicht: "2.445 kg",
    aangedreven: "xDrive vierwielaandrijving",
    introTekst: "De G90 M5 is BMW's meest krachtige sedan ooit. Hybride-technologie levert 1.000 Nm koppel en toch 69 km volledig elektrisch rijden. Dit is niet je vader's M5 — het is zwaarder, krachtiger en technologisch complexer dan ooit.",
    highlights: [
      "Eerste M5 met plug-in hybride aandrijving",
      "1.000 Nm koppel — meer dan een Bugatti Veyron",
      "69 km elektrisch bereik (WLTP)",
      "Automatisch schakelaggregaat met 8 stappen",
      "M Sport uitlaatsysteem met actieve kleppen",
    ],
    doelgroep: "Voor wie het grootste en krachtigste wil, maar ook dagelijks efficiënt wil rijden. Zakelijke rijders profiteren van de lagere bijtelling door de plug-in hybride status.",
    gerelateerdeArtikelSlug: "bmw-m5-koopgids-alle-generaties",
  },
  {
    slug: "bmw-x5-m60i",
    naam: "BMW X5 M60i",
    serie: "X Serie",
    pk: "489 pk",
    koppel: "700 Nm",
    prijs: "€135.000",
    type: "SUV",
    emoji: "🚙",
    kleur: "#27ae60",
    nieuw: false,
    motor: "B58 3.0L Twin-Turbo zes-in-lijn",
    cilinderinhoud: "2.998 cc",
    nulHonderd: "4,3 sec",
    topsnelheid: "250 km/h (begrensd)",
    verbruik: "11,2 l/100 km",
    gewicht: "2.360 kg",
    aangedreven: "xDrive vierwielaandrijving",
    introTekst: "De BMW X5 M60i is de sportieve variant van BMW's meest populaire grote SUV. Meer dan 500 liter kofferbak, zeven zitplaatsen als optie, en toch snel genoeg om een M4 bij te houden van 0 naar 100.",
    highlights: [
      "Optioneel zeven zitplaatsen",
      "Panoramadak standaard in M60i-uitvoering",
      "Integral Active Steering (4-wiel besturing als optie)",
      "Executive Drive Pro adaptieve demping",
      "21 inch M lichtmetalen velgen",
    ],
    doelgroep: "Families die niet willen inleveren op rijplezier. Comfortabel voor lange ritten, krachtig genoeg voor de snelweg en groot genoeg voor alles wat je meeneemt.",
    gerelateerdeArtikelSlug: "5-redenen-bmw-x3-populair",
  },
  {
    slug: "bmw-x3-30i",
    naam: "BMW X3 30i",
    serie: "X Serie",
    pk: "245 pk",
    koppel: "400 Nm",
    prijs: "€62.000",
    type: "SUV",
    emoji: "🚗",
    kleur: "#2ecc71",
    nieuw: true,
    motor: "B46 2.0L TwinPower Turbo viercilinder",
    cilinderinhoud: "1.998 cc",
    nulHonderd: "6,0 sec",
    topsnelheid: "230 km/h (begrensd)",
    verbruik: "7,8 l/100 km",
    gewicht: "1.835 kg",
    aangedreven: "xDrive vierwielaandrijving",
    introTekst: "De BMW X3 is al jaren de bestverkochte BMW in Nederland — en niet zonder reden. De 2024 G45-generatie brengt iDrive 9, een verfijnder interieur en verbeterde elektrificatie. De 30i-variant is het zoete punt in het gamma.",
    highlights: [
      "Volledig vernieuwd iDrive 9 infotainment systeem",
      "Curved display (12,3 + 14,9 inch)",
      "BMW Driving Assistant Pro standaard",
      "550 liter kofferbakruimte",
      "Over-the-air software updates",
    ],
    doelgroep: "De perfecte all-rounder. Groot genoeg voor het gezin, compact genoeg voor de stad en modern genoeg om tien jaar mee te doen.",
    gerelateerdeArtikelSlug: "5-redenen-bmw-x3-populair",
  },
  {
    slug: "bmw-i4-m50",
    naam: "BMW i4 M50",
    serie: "i Serie",
    pk: "544 pk",
    koppel: "795 Nm",
    prijs: "€89.000",
    type: "Elektrisch",
    emoji: "🔋",
    kleur: "#8e44ad",
    nieuw: false,
    motor: "Twee elektromotoren (voor + achter)",
    cilinderinhoud: "83,9 kWh accu (netto)",
    nulHonderd: "3,9 sec",
    topsnelheid: "225 km/h (begrensd)",
    verbruik: "18,5 kWh/100 km (WLTP)",
    gewicht: "2.215 kg",
    aangedreven: "eDrive vierwielaandrijving",
    introTekst: "De BMW i4 M50 bewijst dat elektrisch rijden en rijplezier geen tegenpolen zijn. 544 pk, 3,9 seconden naar 100 en een actieradius tot 510 km. Dit is de M-auto voor de toekomst.",
    highlights: [
      "510 km WLTP actieradius",
      "DC snelladen tot 205 kW",
      "M specifieke aandrijflijntuning met torque vectoring",
      "Iconisch Gran Coupé-silhouet",
      "Recuperatie instelbaar tot 0,3g vertraging",
    ],
    doelgroep: "Rijders die klaar zijn voor elektrisch maar geen concessies willen doen aan rijplezier. Ideaal als lease-auto vanwege lage bijtelling.",
    gerelateerdeArtikelSlug: "bmw-i4-m50-vs-tesla-model-3",
  },
  {
    slug: "bmw-ix-xdrive50",
    naam: "BMW iX xDrive50",
    serie: "i Serie",
    pk: "523 pk",
    koppel: "765 Nm",
    prijs: "€98.000",
    type: "Elektrisch",
    emoji: "⚡",
    kleur: "#9b59b6",
    nieuw: false,
    motor: "Twee elektromotoren (voor + achter)",
    cilinderinhoud: "111,5 kWh accu (netto)",
    nulHonderd: "4,6 sec",
    topsnelheid: "200 km/h (begrensd)",
    verbruik: "19,5 kWh/100 km (WLTP)",
    gewicht: "2.510 kg",
    aangedreven: "eDrive vierwielaandrijving",
    introTekst: "De BMW iX is BMW's visie op de elektrische toekomst. Futuristisch design, revolutionair interieur en tot 630 km actieradius. Dit is geen elektrische auto die op een bestaand platform staat — de iX is van de grond af elektrisch gebouwd.",
    highlights: [
      "630 km WLTP actieradius",
      "DC snelladen tot 200 kW (10-80% in 35 min)",
      "5G connectiviteit en over-the-air updates",
      "Panoramadak met elektrochroom dimming",
      "Interieur met gerecyclede materialen",
    ],
    doelgroep: "Kopers die een premium elektrische SUV willen met maximale actieradius. Concurreert direct met de Mercedes EQS SUV en Audi Q8 e-tron.",
    gerelateerdeArtikelSlug: "bmw-elektrisch-2026-strategie",
  },
  {
    slug: "bmw-3-serie-320i",
    naam: "BMW 3 Serie 320i",
    serie: "3 Serie",
    pk: "184 pk",
    koppel: "300 Nm",
    prijs: "€48.000",
    type: "Sedan",
    emoji: "🚘",
    kleur: "#3498db",
    nieuw: false,
    motor: "B48 2.0L TwinPower Turbo viercilinder",
    cilinderinhoud: "1.998 cc",
    nulHonderd: "7,1 sec",
    topsnelheid: "235 km/h (begrensd)",
    verbruik: "6,3 l/100 km",
    gewicht: "1.540 kg",
    aangedreven: "Achterwielaandrijving",
    introTekst: "De BMW 3 Serie is de meest verkochte BMW ter wereld — en de 320i is de instapmotor die alles goed doet. Licht, zuinig en met de BMW-rijdynamiek intact. De G20-generatie heeft iDrive 8 en een verfijnd chassis.",
    highlights: [
      "Klassieke BMW achterwielaandrijving",
      "iDrive 8 met 10,25 inch touchscreen",
      "BMW Live Cockpit als optie (12,3 + 14,9 inch)",
      "500 liter kofferbakruimte",
      "Mild-hybrid 48V systeem",
    ],
    doelgroep: "De 3 Serie 320i is de beste instap in BMW rijden. Betaalbaar in onderhoud, zuinig op de snelweg en sportief genoeg om plezier te bieden.",
    gerelateerdeArtikelSlug: "bmw-3-serie-occasion-koopadvies",
  },
  {
    slug: "bmw-5-serie-520d",
    naam: "BMW 5 Serie 520d",
    serie: "5 Serie",
    pk: "197 pk",
    koppel: "400 Nm",
    prijs: "€65.000",
    type: "Sedan",
    emoji: "🚖",
    kleur: "#2980b9",
    nieuw: true,
    motor: "B47 2.0L TwinPower Turbo diesel viercilinder",
    cilinderinhoud: "1.995 cc",
    nulHonderd: "6,9 sec",
    topsnelheid: "238 km/h (begrensd)",
    verbruik: "5,1 l/100 km",
    gewicht: "1.760 kg",
    aangedreven: "Achterwielaandrijving (of xDrive optie)",
    introTekst: "De nieuwe G60 BMW 5 Serie is een kwantumsprong ten opzichte van zijn voorganger. Volledig digitaal dashboard, niveau-2 autonome rijfuncties en een diesel die 1 op 20 rijdt op de snelweg. De referentie in de business-klasse.",
    highlights: [
      "Panoramisch gebogen display (12,3 + 14,9 inch)",
      "Parkeren op afstand via smartphone-app",
      "Niveau-2 hands-free rijden op autosnelwegen (optie)",
      "520 liter kofferbakruimte",
      "BMW Personal CoPilot rijhulpsystemen",
    ],
    doelgroep: "Zakelijke rijders en forensen die dagelijks lange afstanden afleggen. De 520d combineert luxe met lage brandstofkosten.",
    gerelateerdeArtikelSlug: "bmw-versus-mercedes-ami",
  },
];

export function getModel(slug: string): BMW | undefined {
  return modellen.find((m) => m.slug === slug);
}
