export interface Motor {
  slug: string;
  naam: string;
  serie: string;
  type: string;
  cc: string;
  pk: string;
  gewicht: string;
  prijs: string;
  emoji: string;
  kleur: string;
  nieuw: boolean;
  beschrijving: string;
  hoogtepunten: string[];
}

export const motoren: Motor[] = [
  // GS Series — Adventure
  {
    slug: "r-1300-gs",
    naam: "BMW R 1300 GS",
    serie: "GS Serie",
    type: "Adventure",
    cc: "1.300 cc",
    pk: "145 pk",
    gewicht: "237 kg",
    prijs: "vanaf €18.750",
    emoji: "🏔️",
    kleur: "#1c69d4",
    nieuw: true,
    beschrijving: "De nieuwe R 1300 GS is de meest capabele GS ooit. Met de nieuwe boxer-twin, verbeterde telelever voorvork en ASA (Automated Shift Assistant) zet hij een nieuwe standaard voor adventure-motorfietsen.",
    hoogtepunten: ["ShiftCam technologie", "Adaptieve rijmodi", "BMW Connectivity", "Hill Start Control", "ASA optioneel"],
  },
  {
    slug: "r-1300-gs-adventure",
    naam: "BMW R 1300 GS Adventure",
    serie: "GS Serie",
    type: "Adventure",
    cc: "1.300 cc",
    pk: "145 pk",
    gewicht: "268 kg",
    prijs: "vanaf €22.400",
    emoji: "🌍",
    kleur: "#1c69d4",
    nieuw: true,
    beschrijving: "De Adventure-versie van de R 1300 GS is gebouwd voor de langste reizen. Groter brandstoftank (30 liter), hogere windscherm en nog robuustere offroad-geometrie.",
    hoogtepunten: ["30 liter tank", "Enduro Pro rijmodus", "Centrale standaard", "Kruiscontrole standaard", "Verhoogde bodemvrijheid"],
  },
  {
    slug: "f-900-gs",
    naam: "BMW F 900 GS",
    serie: "GS Serie",
    type: "Adventure",
    cc: "895 cc",
    pk: "105 pk",
    gewicht: "204 kg",
    prijs: "vanaf €12.500",
    emoji: "🏕️",
    kleur: "#27ae60",
    nieuw: true,
    beschrijving: "De F 900 GS vervangt de F 850 GS en is lichter, wendbaarder en heeft een compleet nieuw ontwerp. Ideaal voor zowel dagelijks gebruik als offroad-uitstapjes.",
    hoogtepunten: ["TFT-kleurendisplay", "Bluetooth connectiviteit", "Cornering ABS", "Rijmodi standaard", "USB-C aansluiting"],
  },
  {
    slug: "f-900-gs-adventure",
    naam: "BMW F 900 GS Adventure",
    serie: "GS Serie",
    type: "Adventure",
    cc: "895 cc",
    pk: "105 pk",
    gewicht: "220 kg",
    prijs: "vanaf €14.200",
    emoji: "⛰️",
    kleur: "#27ae60",
    nieuw: true,
    beschrijving: "Grotere tank, hogere vering en een robuuster frame maken de F 900 GS Adventure klaar voor echte expedities.",
    hoogtepunten: ["23 liter tank", "Spiegelbeugel standaard", "Centerstand", "Enduro rijmodus", "Spoked wheels optioneel"],
  },
  {
    slug: "g-310-gs",
    naam: "BMW G 310 GS",
    serie: "GS Serie",
    type: "Adventure",
    cc: "313 cc",
    pk: "34 pk",
    gewicht: "170 kg",
    prijs: "vanaf €6.300",
    emoji: "🌿",
    kleur: "#2ecc71",
    nieuw: false,
    beschrijving: "De instap-GS. Perfect voor beginners die de GS-filosofie willen ervaren zonder de zware gewichten van de grote broers.",
    hoogtepunten: ["A2-rijbewijs geschikt", "Lichtgewicht", "ABS standaard", "Traction control", "Eenvoudig onderhoud"],
  },

  // S Series — Sportief
  {
    slug: "s-1000-rr",
    naam: "BMW S 1000 RR",
    serie: "S Serie",
    type: "Superbike",
    cc: "999 cc",
    pk: "210 pk",
    gewicht: "197 kg",
    prijs: "vanaf €23.500",
    emoji: "🏁",
    kleur: "#e74c3c",
    nieuw: false,
    beschrijving: "De S 1000 RR is BMW's vlaggenschip superbike en een van de snelste productie-motorfietsen ter wereld. Viercilinder inline motor, ShiftCam, en het meest geavanceerde elektronica-pakket in zijn klasse.",
    hoogtepunten: ["ShiftCam variabele kleptiming", "M Carbon Frame", "Dynamisch traction control", "Launch Control", "BMW Motorrad ABS Pro"],
  },
  {
    slug: "m-1000-rr",
    naam: "BMW M 1000 RR",
    serie: "M Serie",
    type: "Superbike",
    cc: "999 cc",
    pk: "220 pk",
    gewicht: "192 kg",
    prijs: "vanaf €39.900",
    emoji: "🔴",
    kleur: "#c0392b",
    nieuw: false,
    beschrijving: "De M 1000 RR is de meest extreme BMW motorfiets ooit gemaakt. Winglets, carbon onderdelen en een motor die doorloopt tot 15.100 rpm. Gebouwd voor het circuit, legaal op de weg.",
    hoogtepunten: ["220 pk @ 14.500 rpm", "Aerodynamische winglets", "Carbon velgen optioneel", "BMW ShiftCam", "Homologated voor races"],
  },
  {
    slug: "s-1000-r",
    naam: "BMW S 1000 R",
    serie: "S Serie",
    type: "Naked",
    cc: "999 cc",
    pk: "165 pk",
    gewicht: "199 kg",
    prijs: "vanaf €17.200",
    emoji: "⚡",
    kleur: "#e67e22",
    nieuw: false,
    beschrijving: "De naked versie van de S 1000 RR. Zelfde motor, maar meer gericht op rijplezier op de weg. Minder knieligging, meer upright, maar nog steeds ongekend snel.",
    hoogtepunten: ["165 pk viercilinder", "Flexibele rijmodi", "Shift assistant", "Optioneel M-pakket", "Lichter dan RR"],
  },
  {
    slug: "m-1000-r",
    naam: "BMW M 1000 R",
    serie: "M Serie",
    type: "Naked",
    cc: "999 cc",
    pk: "210 pk",
    gewicht: "199 kg",
    prijs: "vanaf €30.500",
    emoji: "💥",
    kleur: "#c0392b",
    nieuw: true,
    beschrijving: "De M 1000 R combineert het volledige RR-motorvermogen met een naked streetfighter-karakter. Dit is de krachtigste naked bike ooit geproduceerd door BMW.",
    hoogtepunten: ["210 pk volledige RR-motor", "M Competition optie: 215 pk", "Carbon kuip", "Winglets", "Slick-klaar chassis"],
  },
  {
    slug: "s-1000-xr",
    naam: "BMW S 1000 XR",
    serie: "S Serie",
    type: "Sport Tourer",
    cc: "999 cc",
    pk: "167 pk",
    gewicht: "226 kg",
    prijs: "vanaf €19.500",
    emoji: "🛣️",
    kleur: "#8e44ad",
    nieuw: false,
    beschrijving: "De S 1000 XR is de sportiefste reismotor in zijn klasse. Viercilinder motor uit de S 1000 RR in een comfortabel reizerschassis — de beste van twee werelden.",
    hoogtepunten: ["167 pk inline-4", "Dynamisch ESA-onderstel", "TFT kleurendisplay", "Kofferhouders standaard", "Cruise control"],
  },

  // R Series — Klassiek & Cruiser
  {
    slug: "r-18",
    naam: "BMW R 18",
    serie: "R Serie",
    type: "Cruiser",
    cc: "1.802 cc",
    pk: "91 pk",
    gewicht: "345 kg",
    prijs: "vanaf €20.100",
    emoji: "🤠",
    kleur: "#f39c12",
    nieuw: false,
    beschrijving: "De BMW R 18 is BMW's antwoord op de American cruiser. De grootste boxer-twin ooit gebouwd door BMW (1.800 cc) in een retro-stijl chassis. Tijdloos en indrukwekkend.",
    hoogtepunten: ["Grootste boxer-twin ooit", "Klassiek chromen design", "Optionele ABS", "Krachtig laag koppel", "R 18 Classic & Transcontinental varianten"],
  },
  {
    slug: "r-nine-t",
    naam: "BMW R nineT",
    serie: "R Serie",
    type: "Heritage / Roadster",
    cc: "1.170 cc",
    pk: "109 pk",
    gewicht: "222 kg",
    prijs: "vanaf €16.800",
    emoji: "🎸",
    kleur: "#95a5a6",
    nieuw: false,
    beschrijving: "De R nineT viert 90 jaar BMW Motorrad. Een moderne motorfiets met retro-DNA. Populair als customizer-basis dankzij de makkelijk te demonteren onderdelen.",
    hoogtepunten: ["Klassieke boxer-twin look", "Demonteerbaar achterdeel", "3 varianten: Scrambler, Pure, Urban G/S", "Optionele ABS Pro", "Tijdloze uitstraling"],
  },

  // K Series — Reizen
  {
    slug: "k-1600-gt",
    naam: "BMW K 1600 GT",
    serie: "K Serie",
    type: "Tourer",
    cc: "1.649 cc",
    pk: "160 pk",
    gewicht: "348 kg",
    prijs: "vanaf €26.800",
    emoji: "🌐",
    kleur: "#2c3e50",
    nieuw: false,
    beschrijving: "De K 1600 GT is gebouwd voor de rijder die comfort en prestaties weigert te compromitteren. Zescilinder lijnmotor, volledige integratie en luxe afwerking.",
    hoogtepunten: ["6-cilinder inline motor", "Actief onderstel", "Verwarmd zadel standaard", "Radar-gestuurde ACC", "Hi-fi audiosysteem"],
  },
  {
    slug: "k-1600-gtl",
    naam: "BMW K 1600 GTL",
    serie: "K Serie",
    type: "Tourer",
    cc: "1.649 cc",
    pk: "160 pk",
    gewicht: "367 kg",
    prijs: "vanaf €29.200",
    emoji: "🏡",
    kleur: "#2c3e50",
    nieuw: false,
    beschrijving: "De GTL is de comfortabelste versie van de K 1600-familie. Extra windscherm, luxer zadel en meer opbergruimte voor de lange reiziger.",
    hoogtepunten: ["Extra hoog windscherm", "Comfortzadel bestuurder & passagier", "Volledige kofferset", "Reverse gear", "Integraal helmslot"],
  },

  // F Series — Middenklasse
  {
    slug: "f-900-r",
    naam: "BMW F 900 R",
    serie: "F Serie",
    type: "Naked",
    cc: "895 cc",
    pk: "105 pk",
    gewicht: "193 kg",
    prijs: "vanaf €10.200",
    emoji: "🔥",
    kleur: "#e67e22",
    nieuw: false,
    beschrijving: "De F 900 R is BMW's meest toegankelijke naked bike. Lichter, makkelijker te besturen en toch spannend genoeg voor de ervaren rijder.",
    hoogtepunten: ["105 pk paralleltwin", "Laag zwaartepunt", "TFT display", "3 rijmodi", "Sporty & Compact"],
  },
  {
    slug: "f-900-xr",
    naam: "BMW F 900 XR",
    serie: "F Serie",
    type: "Sport Tourer",
    cc: "895 cc",
    pk: "105 pk",
    gewicht: "219 kg",
    prijs: "vanaf €12.000",
    emoji: "🗺️",
    kleur: "#27ae60",
    nieuw: false,
    beschrijving: "De F 900 XR combineert sport en touring in een betaalbaar pakket. Een uitstekende instap in de adventure sport-wereld.",
    hoogtepunten: ["Sport tourer geometrie", "Windscherm verstelbaar", "Kofferhouders optioneel", "Cruise control", "105 pk voor elke dag"],
  },

  // G Series — Instap
  {
    slug: "g-310-r",
    naam: "BMW G 310 R",
    serie: "G Serie",
    type: "Naked",
    cc: "313 cc",
    pk: "34 pk",
    gewicht: "158 kg",
    prijs: "vanaf €5.500",
    emoji: "🌱",
    kleur: "#2ecc71",
    nieuw: false,
    beschrijving: "De G 310 R is de perfecte instapmotor voor beginnende rijders. Licht, makkelijk te besturen en betrouwbaar — maar toch met het BMW-logo.",
    hoogtepunten: ["A2-rijbewijs geschikt", "Lichtst in zijn klasse", "ABS standaard", "Stadsmobiliteit", "Laag zitcomfort: 785 mm"],
  },

  // CE — Elektrisch
  {
    slug: "ce-04",
    naam: "BMW CE 04",
    serie: "CE Serie",
    type: "Elektrische Scooter",
    cc: "Elektrisch",
    pk: "42 pk",
    gewicht: "231 kg",
    prijs: "vanaf €12.900",
    emoji: "🔋",
    kleur: "#1abc9c",
    nieuw: false,
    beschrijving: "De CE 04 is BMW's futuristische elektrische scooter. Futuristisch design, snelle laadtijd (1,5 uur snel laden) en een actieradius van 130 km. Perfecte stadsmobiliteit.",
    hoogtepunten: ["130 km actieradius", "1,5 uur snel laden (DC)", "6,5-inch TFT display", "Smartphone integratie", "Rijdt als een M-auto voor de stad"],
  },
];

export function getMotor(slug: string): Motor | undefined {
  return motoren.find((m) => m.slug === slug);
}

export const motorSeries = [...new Set(motoren.map((m) => m.serie))];
